// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgbbKoP34GCn24Z_VYCDUWI14mATho6Zk',
    appId: '1:362094883561:web:2651666017ff5ed8547678',
    messagingSenderId: '362094883561',
    projectId: 'fooddeliveryflutter-fa8b7',
    authDomain: 'fooddeliveryflutter-fa8b7.firebaseapp.com',
    storageBucket: 'fooddeliveryflutter-fa8b7.appspot.com',
    measurementId: 'G-2CNZ2FD00Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR96Pc-1NELdbOD8I9ucHSC1s6Rnl3YYc',
    appId: '1:362094883561:android:4b5251f35517faa8547678',
    messagingSenderId: '362094883561',
    projectId: 'fooddeliveryflutter-fa8b7',
    storageBucket: 'fooddeliveryflutter-fa8b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgQXROilYtxCNh1InRk9vvCQqMQ2G0ySY',
    appId: '1:362094883561:ios:71cfb24d9391ca92547678',
    messagingSenderId: '362094883561',
    projectId: 'fooddeliveryflutter-fa8b7',
    storageBucket: 'fooddeliveryflutter-fa8b7.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgQXROilYtxCNh1InRk9vvCQqMQ2G0ySY',
    appId: '1:362094883561:ios:71cfb24d9391ca92547678',
    messagingSenderId: '362094883561',
    projectId: 'fooddeliveryflutter-fa8b7',
    storageBucket: 'fooddeliveryflutter-fa8b7.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgbbKoP34GCn24Z_VYCDUWI14mATho6Zk',
    appId: '1:362094883561:web:b163c364c7ea11f6547678',
    messagingSenderId: '362094883561',
    projectId: 'fooddeliveryflutter-fa8b7',
    authDomain: 'fooddeliveryflutter-fa8b7.firebaseapp.com',
    storageBucket: 'fooddeliveryflutter-fa8b7.appspot.com',
    measurementId: 'G-M5GGE9TZ8R',
  );
}
